name: expression
channels:
 - conda-forge
 - bioconda
dependencies:
 - r-base >= 4.1.0
 - r-tidyverse >= 1.3.0
 - r-wgcna >= 1.69
 - r-rcolorbrewer >= 1.1_2
 - bioconductor-biomart >= 2.48.0
 - bioconductor-clusterprofiler >= 4.0.0
 - bioconductor-reactomepa >= 1.36.0
 - bioconductor-org.hs.eg.db >= 3.13.0
 - bioconductor-go.db >= 3.13.0                 #  Required for WGCNA
 - bioconductor-impute >= 1.66.0                #  Required for WGCNA
 - bioconductor-preprocesscore >= 1.54.0        #  Required for WGCNA
 - r-rocr >= 1.0_11
 - bioconductor-mofa2 >= 1.2.0