name: expression
channels:
 - conda-forge
 - bioconda
dependencies:
 - jupyterlab >= 3.2.1
 - r-base >= 4.0.0
 - r-irkernel                                   # Required for Jupyter Notebook integration
 - r-tidyverse
 - r-wgcna
 - r-rcolorbrewer
 - r-cowplot
 - r-svglite                                    #  Required for ggplot2 SVG
 - r-enrichr
 - bioconductor-biomart
 - bioconductor-go.db                           #  Required for WGCNA
 - bioconductor-impute                          #  Required for WGCNA
 - bioconductor-preprocesscore                  #  Required for WGCNA
