name: jupyterlab
channels:
 - conda-forge
 - bioconda
dependencies:
 - jupyterlab >= 3.2.1
 - r-base >= 4.0.0
 - r-irkernel
 - r-tidyverse
 - r-rcolorbrewer
 - r-svglite                                    #  Required for ggplot2 SVG
