name: colocalization
channels:
 - conda-forge
 - bioconda
dependencies:
 - nextflow >= 21.04.0
 - r-base >= 4.1.0
 - r-tidyverse >= 1.3.0
 - r-reticulate >= 1.22
 - r-remotes >= 2.4.1
 - r-susier >= 0.11
 - vcftools >= 0.1.16
 - bcftools >= 1.14
 - bedtools >= 2.30.0
