name: functional_interpretation
channels:
 - conda-forge
 - bioconda
dependencies:
 - jupyterlab >= 3.2.1
 - r-base >= 4.0.0
 - r-irkernel
 - r-tidyverse
 - r-rcolorbrewer
 - r-svglite                                    #  Required for ggplot2 SVG
 - nextflow >= 21.04.0
 - sra-tools >= 2.11.0
 - fastqc >= 0.11.9
 - trim-galore >= 0.6.7
 - star >= 2.7.9a
 - bowtie2 >= 2.4.4
 - samtools >= 1.13
 - bedtools >= 2.30.0
 - picard >= 2.26.3
 - macs2 >= 2.2.7.1
 - subread >= 2.0.1
 - rseqc >= 4.0.0
 - click >= 8.0.1
 - pandas >= 1.3.3
 - multiqc >= 1.11
 - pysam >= 0.17.0
 - qualimap >= 2.2.2d
