channels:

 - conda-forge
 - bioconda

dependencies:

# Nextflow
 - nextflow >= 21.04.0

# Jupyter Lab
 - jupyterlab >= 3.2.1
 - r-base >= 4.0.0
 - r-irkernel

# R Packages for Data Analysis
 - r-tidyverse
 - r-rcolorbrewer
 - r-svglite                                    #  Required for ggplot2 SVG

# BioConductor
 - bioconductor-biomart

# Bioinformatics Tools
 - vcftools >= 0.1.16
 - bcftools >= 1.14
 - bedtools >= 2.30.0
 - sra-tools >= 2.11.0
 - fastqc >= 0.11.9
 - trim-galore >= 0.6.7
 - star >= 2.7.9a
 - bowtie2 >= 2.4.4
 - samtools >= 1.13
 - picard >= 2.26.3
 - macs2 >= 2.2.7.1
 - subread >= 2.0.1
 - rseqc >= 4.0.0
 - multiqc >= 1.11
 - pysam >= 0.17.0
 - qualimap >= 2.2.2d
 - plink >= 1.90b6.21
 - r-wgcna
 - bioconductor-go.db                           #  Required for WGCNA
 - bioconductor-impute                          #  Required for WGCNA
 - bioconductor-preprocesscore                  #  Required for WGCNA
